---
name: CI

on:
  push:
    branches:
      - feature/ci
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install the dependencies
        run: |
          groups $USER
          ls -la
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - uses: seisollc/easy_infra@make_github_action
        with:
          command: terraform init
